  
name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project 2
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/VESPERStudios/projects/2'
        column_name: 'Needs triage'
  assign_central_project:
    runs-on: ubuntu-latest
    name: Assign to Central Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project 10
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/VESPERStudios/projects/12'
        column_name: 'Bug Reports'
